name: novel-develop
on:
    push:
        branches: [develop]
jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: yarn install
            - run: tsc
    deploy:
        name: Deploy
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: deploy
              uses: appleboy/ssh-action@master
              with:
                  host: 103.154.177.218 #hostname of server
                  username: root #username login to server
                  password: Y$=6-aArL6jP&Eq6 #password login to server
                  port: 7878 #port of server - often port is 22
                  script: | # run with multiple script
                      cd outsource-app-truyen-full
                      git pull
                      yarn
                      pm2 start ecosystem.json
